"""empty message

Revision ID: 49a38b5f542b
Revises: e81f0f13946a
Create Date: 2020-12-08 12:42:10.297821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a38b5f542b'
down_revision = 'e81f0f13946a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('category', sa.String(length=250), nullable=True))
    op.execute("UPDATE car SET category = 'Autos'")
    op.alter_column('car', 'category', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'categoria')
    # ### end Alembic commands ###
