"""empty message

Revision ID: 9cf8c5b6c6dd
Revises: 
Create Date: 2021-01-21 11:05:49.322964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf8c5b6c6dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'doc_type', nullable=False, new_column_name='subtitulo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'subtitulo', nullable=False, new_column_name='doc_type')
    # ### end Alembic commands ###
