"""empty message

Revision ID: 9f8e5d3fed7c
Revises: 49a38b5f542b
Create Date: 2021-01-20 15:47:52.874835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e5d3fed7c'
down_revision = '49a38b5f542b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'doc_type', nullable=False, new_column_name='subtitulo')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'subtitulo', nullable=False, new_column_name='doc_type')
    # ### end Alembic commands ###
